/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamma.cvd.calculator.gui.menu;

import gamma.cvd.calculator.gui.GuiUtils;
import gamma.cvd.calculator.gui.calculator.CalculatorScreen;

/**
 *
 * @author Jack
 */
public class MainMenuScreen extends javax.swing.JFrame
{

    /**
     * Creates new form MainMenuScreen
     */
    public MainMenuScreen()
    {
        initComponents();
        GuiUtils.centerScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        imgLoginIcon = new javax.swing.JLabel();
        btnNewPatient = new javax.swing.JButton();
        btnExistingPatient = new javax.swing.JButton();
        imgMainMenuIcon = new javax.swing.JLabel();

        imgLoginIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jack\\Documents\\GitHub\\CVDCalculator\\resources\\icons\\logo.png")); // NOI18N
        imgLoginIcon.setName("imgCalculatorIcon"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NHS CVD Calculator - Menu");

        btnNewPatient.setText("New Patient");
        btnNewPatient.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewPatientActionPerformed(evt);
            }
        });

        btnExistingPatient.setText("Existing Patient");

        imgMainMenuIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jack\\Documents\\GitHub\\CVDCalculator\\resources\\icons\\logo.png")); // NOI18N
        imgMainMenuIcon.setName("imgCalculatorIcon"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgMainMenuIcon)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnExistingPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(btnNewPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(imgMainMenuIcon)
                .addGap(25, 25, 25)
                .addComponent(btnNewPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExistingPatient)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewPatientActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewPatientActionPerformed
    {//GEN-HEADEREND:event_btnNewPatientActionPerformed
        dispose();
        new CalculatorScreen().setVisible(true);
    }//GEN-LAST:event_btnNewPatientActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExistingPatient;
    private javax.swing.JButton btnNewPatient;
    private javax.swing.JLabel imgLoginIcon;
    private javax.swing.JLabel imgMainMenuIcon;
    // End of variables declaration//GEN-END:variables
}
