package gamma.cvd.calculator.gui.login;

import gamma.cvd.calculator.gui.GuiUtils;
import gamma.cvd.calculator.gui.menu.MainMenuScreen;
import gamma.cvd.login.CVDLogin;
import gamma.cvd.login.PasswordHash;
import java.io.File;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.xml.xpath.XPathExpressionException;
import org.xml.sax.SAXException;


/**
 *
 * @author Jack
 */
public class LoginScreen extends javax.swing.JFrame
{
    
    private CVDLogin auth;
    /**
     * Creates new form LoginScreen
     */
    public LoginScreen()
    {
        final String WORK_DIR = System.getProperty("user.dir");
        final String ICON_DIR = "/resources/icons/";
        
        try {
            this.auth = new CVDLogin();
            
            initComponents();
            
            imgLoginIcon.setIcon(new ImageIcon(ImageIO.read(new File(WORK_DIR + ICON_DIR + "logo.png"))));
            
            GuiUtils.setNativeGuiStyle(this);
            
            // Center screen
            GuiUtils.centerScreen(this);
            GuiUtils.setNativeGuiStyle(this);
            
        } catch (SAXException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (XPathExpressionException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (GeneralSecurityException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        txtLoginUsername = new javax.swing.JTextField();
        lblLoginUsername = new javax.swing.JLabel();
        lblLoginPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnAccessRegistration = new javax.swing.JButton();
        txtLoginPassword = new javax.swing.JPasswordField();
        imgLoginIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NHS CVD Risk Calculator");

        txtLoginUsername.setName("txtLoginUsername"); // NOI18N
        txtLoginUsername.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtLoginUsernameActionPerformed(evt);
            }
        });

        lblLoginUsername.setText("Username: ");
        lblLoginUsername.setName("lblLoginUsername"); // NOI18N

        lblLoginPassword.setText("Password: ");
        lblLoginPassword.setName("lblLoginPassword"); // NOI18N

        btnLogin.setText("Login");
        btnLogin.setName("btnLogin"); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLoginActionPerformed(evt);
            }
        });

        btnAccessRegistration.setText("Register");
        btnAccessRegistration.setActionCommand("btnRegister");
        btnAccessRegistration.setName("btnAccessRegistration"); // NOI18N
        btnAccessRegistration.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAccessRegistrationActionPerformed(evt);
            }
        });

        txtLoginPassword.setName("txtLoginPassword"); // NOI18N

        imgLoginIcon.setName("imgCalculatorIcon"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAccessRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoginPassword)
                            .addComponent(lblLoginUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoginPassword)
                            .addComponent(txtLoginUsername))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgLoginIcon)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLoginIcon)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginUsername)
                    .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginPassword)
                    .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccessRegistration)
                    .addComponent(btnLogin))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginUsernameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtLoginUsernameActionPerformed
    {//GEN-HEADEREND:event_txtLoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUsernameActionPerformed

    private void btnAccessRegistrationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAccessRegistrationActionPerformed
    {//GEN-HEADEREND:event_btnAccessRegistrationActionPerformed
        
             new RegistrationPromptScreen(auth).setVisible(true);    
    }//GEN-LAST:event_btnAccessRegistrationActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLoginActionPerformed
    {//GEN-HEADEREND:event_btnLoginActionPerformed
        
        if (txtLoginUsername.getText().isEmpty() || txtLoginPassword.getPassword().length == 0)
        {
            JOptionPane.showMessageDialog(this, "Please fill the correct fields in with your desired username and password", "Insufficient Details", JOptionPane.WARNING_MESSAGE);          
        }
        else
        { 
            try {
                String username = txtLoginUsername.getText();
                String password = Arrays.toString(txtLoginPassword.getPassword());

                boolean loginIsValid = auth.validateUsernameAndPassword(username, password);
                
                if (!loginIsValid)
                {
                    JOptionPane.showMessageDialog(this, "Incorrect username/password combination used, please enter your correct username and password", "Invalid Login", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    dispose();            
                    new MainMenuScreen().setVisible(true);
                }
            } catch (NoSuchAlgorithmException | InvalidKeySpecException | XPathExpressionException ex) {
                Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccessRegistration;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel imgLoginIcon;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JPasswordField txtLoginPassword;
    private javax.swing.JTextField txtLoginUsername;
    // End of variables declaration//GEN-END:variables
}
