package gamma.cvd.calculator.gui.login;

import gamma.cvd.calculator.gui.GuiUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author Jack
 */
public class RegistrationPromptScreen extends javax.swing.JFrame
{
    private static final String REGISTRATION_KEY = "472KiNz8Un"; 
    
    /**
     * Creates new form RegistrationCodePromptScreen
     */
    public RegistrationPromptScreen()
    {
        initComponents();
        
        GuiUtils.setNativeGuiStyle(this);    
        GuiUtils.centerScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblRegistrationKey = new javax.swing.JLabel();
        txtRegistrationKey = new javax.swing.JTextField();
        btnEnterKey = new javax.swing.JButton();
        btnRegistrationClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter your Registration Key");

        lblRegistrationKey.setText("Registration Key");

        btnEnterKey.setText("Enter Key");
        btnEnterKey.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEnterKeyActionPerformed(evt);
            }
        });

        btnRegistrationClose.setText("Close");
        btnRegistrationClose.setActionCommand("btnClose");
        btnRegistrationClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrationCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRegistrationKey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRegistrationKey, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnterKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrationClose, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistrationKey)
                    .addComponent(txtRegistrationKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnterKey)
                    .addComponent(btnRegistrationClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterKeyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEnterKeyActionPerformed
    {//GEN-HEADEREND:event_btnEnterKeyActionPerformed
       if (!txtRegistrationKey.getText().equals(REGISTRATION_KEY))
       {
            JOptionPane.showMessageDialog(this, "The key entered was incorrect.", "Incorrect Key", JOptionPane.ERROR_MESSAGE);          
       }
       else
       {
           // Call Registration Method with username & password
           JOptionPane.showMessageDialog(this, "Account was succesfully registered, you may now login with your new details", "Succesful Registration", JOptionPane.INFORMATION_MESSAGE);          
           dispose(); 
       }
    }//GEN-LAST:event_btnEnterKeyActionPerformed

    private void btnRegistrationCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrationCloseActionPerformed
    {//GEN-HEADEREND:event_btnRegistrationCloseActionPerformed
           dispose(); 
    }//GEN-LAST:event_btnRegistrationCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RegistrationPromptScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RegistrationPromptScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RegistrationPromptScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RegistrationPromptScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RegistrationPromptScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterKey;
    private javax.swing.JButton btnRegistrationClose;
    private javax.swing.JLabel lblRegistrationKey;
    private javax.swing.JTextField txtRegistrationKey;
    // End of variables declaration//GEN-END:variables
}
